name: Clone backend + frontend and deploy images to AWS ECR

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout integration repo (this one)
        uses: actions/checkout@v3

      - name: Checkout torahai backend repo
        uses: actions/checkout@v3
        with:
          repository: jc-773/torahAI_backend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: torahai-backend

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Unit Tests
        run: |
          cd torahai-backend
          ./mvnw test

      - name: Build maven project
        run: |
          cd torahai-backend
          ./mvnw clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest-backend
          docker build -t $IMAGE_URI ./torahai-backend
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Debug constructed image URI
        run: |
            IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest-backend
            echo "Constructed IMAGE_URI = $IMAGE_URI"

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Checkout torahai frontend repo
        uses: actions/checkout@v3
        with:
          repository: jc-773/torah_ai
          token: ${{ secrets.GITHUB_TOKEN }}
          path: torahai-frontend

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.13.1' 
       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

        #sets the image uri and builds "." (directory from Dockerfile)
      - name: Build and tag Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest-frontend
           docker build -t $IMAGE_URI ./torahai-frontend
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push image to ECR
        run: |
          docker push $IMAGE_URI